[build-system]
requires = ["hatchling", "pandas", "scikit-learn", "seaborn", "matplotlib"]
build-backend = "hatchling.build"

[project]
name = "HYBparsiomny"
version = "0.0.4"
authors = [
  { name="Jose Divasón", email="jose.divason@unirioja.es" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/jodivaso/hyb-parsimony"